openapi: 3.0.3
info:
  title: DBP
  description: |-
    See github documentation at https://github.com/GaudiLabs/DigitalBiologyPlatform
  termsOfService: https://github.com/GaudiLabs/DigitalBiologyPlatform
  contact:
    email: apiteam@swagger.io
  version: 1.0.11
#commented because causing deployment problems
#TODO : investigate
#servers:
#  - url: https://nohostnamefornow.io
#  - url: http://localhost:8080
#  - url: https://dbp-backend-api-production.up.railway.app
tags:
  - name: user
    description: Operations about users
  - name: protocol
    description: Operations about protocols
  - name: swagger
    description: Operations about swagger
paths:
  /swagger.json:
    get:
      tags:
        - swagger
      summary: Serve a json file representing this swaggerfile
      description: ''
      operationId: serveSwaggerFile
      responses:
        '200':
          description: successful operation
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: Create a user
      operationId: createUser
      requestBody:
        description: Created user object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserParams'
      responses:
        default:
          description: successful operation
  /user/{username}:
    get:
      tags:
        - user
      summary: get a user
      description: get a user
      operationId: getUser
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: username of an user
      responses:
        '404':
          description: User not found
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicUser'  

  /user/login:
    post:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      requestBody:
        description: Request access token via username/password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginParams'
      responses:
        '201':
          description: successful operation, token created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginToken'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '400':
          $ref: '#/components/responses/BadRequestError'
  /user/me:
    get:
      security:
        - BearerAuth: []
      tags:
        - user
      summary: Get user infos of token bearer
      description: ''
      operationId: getSelfUser
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
        '404':
          description: User not found
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '400':
          $ref: '#/components/responses/BadRequestError'
  /protocol/me:
    get:
      security:
        - BearerAuth: []
      tags:
        - protocol
      summary: Get token bearer protocols list
      description: return a list of protocols created by this user
      operationId: getSelfProtocolList
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortProtocolsList'
  /public/protocol/all:
    get:
      tags:
        - protocol public
      summary: Get public protocols list
      description: return a list of public protocols
      operationId: getPublicProtocolsList
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortProtocolsList'
  /protocol/{protocolID}:
    get:
      security:
        - BearerAuth: []
      tags:
        - protocol
      summary: Get a particular protocol by its ID
      description: return a protocol
      parameters:
        - in: path
          name: protocolID
          schema:
            type: integer
          required: true
          description: Numeric ID of the protocol to get
      operationId: getProtocol
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullProtocol'
    put:
      security:
        - BearerAuth: []
      tags:
        - protocol
      summary: update a particular entire protocol by its ID
      description: overwrite a protocol
      requestBody:
        description: Protocol description in json
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadProtocolParams'
      parameters:
        - in: path
          name: protocolID
          schema:
            type: integer
          required: true
          description: Numeric ID of the protocol to overwrite
      operationId: overwriteProtocol
      responses:
        default:
          description: successful operation
    delete:
      security:
        - BearerAuth: []
      tags:
        - protocol
      summary: delete a particular entire protocol by its ID
      description: delete a protocol
      parameters:
        - in: path
          name: protocolID
          schema:
            type: integer
          required: true
          description: Numeric ID of the protocol to delete
      operationId: deleteProtocol
      responses:
        default:
          description: successful operation
  /public/protocol/{protocolID}:
    get:
      tags:
        - protocol
      summary: Get a particular protocol by its ID
      description: return a protocol
      parameters:
        - in: path
          name: protocolID
          schema:
            type: integer
          required: true
          description: Numeric ID of the protocol to get
      operationId: getPublicProtocol
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullProtocol'

  /hardware/device/all:
    get:
      tags:
        - hardware
      summary: Get a particular dive infos by its ID
      description: return a list of electrodes compatible with the device, its name, its svg
      operationId: getDevices
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/FullDevice'
  /protocol:
    post:
      security:
        - BearerAuth: []
      tags:
        - protocol
      summary: Upload a protocol
      description: Upload a protocol to the server
      requestBody:
        description: Protocol description in json
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadProtocolParams'
      operationId: uploadProtocol
      responses:
        default:
          description: successful operation
          #content:
            #application/json:
              # schema:
              #   $ref: '#/components/schemas/FullProtocol'
 
 
components:
  responses:
    UnauthorizedError:
      description: Authentication information is present but wrong
    BadRequestError:
      description: Request body is baddly formated, authentication information is missing or invalid


  schemas:
    UploadProtocolParams:
      type : object
      required: 
        - "name"
        - "frames"
        - "author_list"
        - "device_id"
        - "public"
      properties: 
        device_id:
          type: "number"
        name: 
          type: "string"
        description: 
          type: "string"
        frames: 
          type: "array"
          items: 
            $ref : '#/components/schemas/Frame'
        author_list: 
          type: "array"
          items: 
            $ref: '#/components/schemas/RankedAuthor'
        public: 
          type: "boolean"

    FullDevice:
      type : object
      required: 
        - "id"
        - "name"
        - "electrodes"
        - "svg"
      properties: 
        id: 
          type: "number"
        name: 
          type: "string"
        electrodes: 
          type: "array"
          items: 
            type : string

    FullProtocol:
      type : object
      required: 
        - "id"
        - "name"
        - "frames"
        - "authors"
        - "frame_count"
        - "total_duration"
        - "device_id"
        - "public"
      properties: 
        id: 
          type: "number"
        device_id:
          type: "number"
        name: 
          type: "string"
        description: 
          type: "string"
        frames: 
          type: "array"
          items: 
            $ref : '#/components/schemas/Frame'
        author_list: 
          type: "array"
          items: 
            $ref: '#/components/schemas/RankedAuthor'
        frame_count: 
          type: "number"
        total_duration: 
          type: "number"
        public: 
          type: "boolean"



    Electrode:
      type: object
      required: 
        - "value"
        - "electrode_id"
      properties: 
        value: 
          type: "number"
        electrode_id: 
          type: "string"

    Frame:
      type: object
      required: 
        - "duration"
        - "rank"
        - "electrodes"
      properties: 
        duration: 
          type: "number"
        rank: 
          type: "number"
        temperatures: 
          type: "array"
          items:
             $ref: '#/components/schemas/IndexedTemperature'
        magnets: 
          type: "array"
          items:
             $ref: '#/components/schemas/IndexedMagnet'
        electrodes: 
          type: "array"
          items:
             $ref: '#/components/schemas/Electrode'

    RankedAuthor:
      type: object
      required: 
        - "rank"
        - "author"
      properties: 
        rank: 
          type: "number"
        author: 
          type: "string"

    IndexedTemperature:
      type: object
      required: 
        - "index"
        - "value"
      properties: 
        index: 
          type: "number"
        value: 
          type: "number"

    IndexedMagnet:
      type: object
      required: 
        - "index"
        - "value"
      properties: 
        index: 
          type: "number"
        value: 
          type: "boolean"

    ShortProtocol:
      type: object
      required: 
        - "id"
        - "name"
        - "mask_frame"
        - "author_list"
        - "author_rank"
        - "frame_count"
        - "total_duration"
        - "description"
        - "device_id"
        - "public"
      properties: 
        id: 
          type: "number"
        device_id:
          type: "number"
        name: 
          type: "string"
        description: 
          type: "string"
        mask_frame: 
          type: "array"
          items: 
            $ref : '#/components/schemas/Frame'
        author_list: 
          type: "array"
          items: 
            $ref: '#/components/schemas/RankedAuthor'
        author_rank: 
          type: "number"
        frame_count: 
          type: "number"
        total_duration: 
          type: "number"
        public: 
          type: "boolean"



 
    ShortProtocolsList:
      type: object
      required: 
        - "protocols"
      properties:
        protocols:
          type: array
          items:
            $ref: '#/components/schemas/ShortProtocol'
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        email:
          type: string
          example: john@email.com
        tokens:
          type: array
          items:
            $ref: '#/components/schemas/LoginToken'
      xml:
        name: user

    PublicUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        fullname:
          type: string
          example: 'John Doe'
        institution:
          type: string
          example: 'Universsity of Somewhere'
        website:
          type: string
          example: 'https://website.com'
        email:
          type: string
          example: john@email.com
        bio:
          type: string
          example: "I am a enginner who likes cats."
        protocol_amount:
          type: integer
          example: 12
        public_protocol_amount:
          type: integer
          example: 10
 
    LoginToken:
      type: object
      properties:
        token:
          type: string
          example: "Xz5Re76tlCTYddIVwUOpBI"
        expiration_date:
          type: string
          example: "2012-04-23T18:25:43.511Z"
      xml:
        name: user
    LoginParams:
      type: object
      required:
        - "username"
        - "password"
      properties:
        username:
          type: string
          example: theUser
        password:
          type: string
          example: "Userpass"
      xml:
        name: user
    CreateUserParams:
      type: object
      required: 
        - "username"
        - "password"
        - "captcha_token"
      properties:
        username:
          type: string
          example: theUser
        bio:
          type: string
          example: "I am a enginner who likes cats."
        password:
          type: string
          example: "Userpass"
        email:
          type: string
          example: "a.b@c.d"
        fullname:
          type: string
          example: 'John Doe'
        institution:
          type: string
          example: 'Universsity of Somewhere'
        website:
          type: string
          example: 'https://website.com'
        captcha_token:
          type: string
      xml:
        name: user
 
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

