// Package test provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package server

import (
	//"errors"
	"net/http"

	"github.com/davecgh/go-spew/spew"
	"github.com/labstack/echo/v4"
)

type Handlers struct {
	data string
}

func NewHandlers() *Handlers {
	return &Handlers{data: "oh"}
}

// CreateUser converts echo context to params.
func (w *Handlers) CreateUser(ctx echo.Context) error {
	ctx.String(http.StatusOK, "Hello, World!")

	return nil
}

// LoginUser converts echo context to params.
func (w *Handlers) LoginUser(ctx echo.Context, params LoginUserParams) error {
	spew.Dump(params)
	if (params.Username == nil || params.Password == nil){
		ctx.String(http.StatusUnprocessableEntity, "Unable to process the request")
		spew.Dump(ctx)
		//return errors.New(ctx.Response().S, ctx.Request().Response)
		return nil
	}
	if *params.Username != "uname" && *params.Password != "password" {
		ctx.String(http.StatusUnauthorized, "Unauthorized")
	}
		ctx.String(http.StatusOK, "Hello, World!")
	return nil
}

// LogoutUser converts echo context to params.
func (w *Handlers) LogoutUser(ctx echo.Context) error {
	ctx.String(http.StatusOK, "Hello, World!")

	return nil
}

// DeleteUser converts echo context to params.
func (w *Handlers) DeleteUser(ctx echo.Context, username string) error {
	ctx.String(http.StatusOK, "Hello, World!")

	return nil
}

// GetUserByName converts echo context to params.
func (w *Handlers) GetUserByName(ctx echo.Context, username string) error {
	ctx.String(http.StatusOK, "Hello, World!")

	return nil
}

// UpdateUser converts echo context to params.
func (w *Handlers) UpdateUser(ctx echo.Context, username string) error {
	ctx.String(http.StatusOK, "Hello, World!")

	return nil
}
